import React from 'react';
import Header from '@/components/Header';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={({margin: 0, padding: 0,})}>
        <Header />
        <main>
          {children}
        </main>
      </body>


    </html>
  )
}
export const dynamic = 'force-dynamic';
